creme/stream.py
Hello! 
First of all, great work on this project. It has a lot of potential! I really hope it will continue to grow and improve. 
This is just a small PR which adds a function to iterate over `vaex` DataFrames. 
Here is a minimal working example (screen-shot)
[Vaex](https://github.com/vaexio/vaex) is a DataFrame library (ala) `pandas`, but specialized for working with much larger datasets that do not fit onto the memory of a single computer. In a way, it shares similar concepts to `creme`, i.e. computing statistics in chunks. 
I can see these libraries working well together. I agree that for taking models to production, monitoring etc.. online learning makes a lot of sense, and is something I am considering for my upcoming models. But sometimes one does have plenty of data to experiment …
=> Adding iter_vaex, to stream data from vaex.dataframe

creme/ensemble/__init__.py, creme/ensemble/boosting.py, creme/test_.py, docs/api.rst
Hi, 
Here is AdaboostClassifier. 🤙
The results are interesting. On trees I got better results than a simple decision tree but not as good as a Random Forest. However, Adaboost can be used to make Boosted  Random Forest and the results are better than a single random Forest (very long execution time because the calculations are sequential).
I made a draft pull request because I didn't implement the predict_one method correctly.
The "online_score" method of the "model_selection" class calls by default predict_one for AdaboostClassifier while on BaggingClassifier it calls by default predict_proba_one. I missed something here, I think...
```python
model_selection.online_score(X_y, model, metric) # Call predict_one by default for AdaboostClassifier even if metric is LogLoss
``` 
First boosting …
=> AdaboostClassifier

creme/optim/ada_bound.py
I was trying various optimizers in loop and accidentally run AdaBound with `schedulers` and got `TypeError: unsupported operand type(s) for /: 'float' and 'InverseScaling'` at line 70.
Because `AdaBound` is implicitly changing `lr` and don't require `scheduler`. So it is better to raise an error if in case user uses non-numeric `lr` because the default error is non-informatic.
=> minor AdaBound fix

ci/test.sh
[flake8](http://flake8.pycqa.org) testing of https://github.com/creme-ml/creme on Python 3.8.0
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./creme/reco/baseline.py:80:65: F821 undefined name 'u_optimizer'
self.loss = optim.losses.Squared() if loss is None else u_optimizer
^
1     F821 undefined name 'u_optimizer'
1
```
https://flake8.pycqa.org/en/latest/user/error-codes.html
Also, pip will soon have a real dependancy resolver so it is better to give it more requirements in a single command so that it can a more complete job of resolving the dependancies.
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests …
=> CI: Lint for undefined names in Python code

creme/tree/base.py
@MaxHalford Setting the default value of the depth parameter of the iter_dfs method from class Leaf solve the error. Is there any side effect? 
```
from creme import datasets
from creme import tree
model = tree.DecisionTreeClassifier(
confidence=1e-50,
)
for x, y in datasets.Phishing():
model.fit_one(x, y)
model.draw(2)
```
=> Hotfix - Error with DecisionTreeClassifier.draw() #272

creme/compat/creme_to_sklearn.py, creme/compat/sklearn_to_creme.py, creme/compat/test_sklearn.py
Also fix the Creme2SKLClassifier so it passes scikit-learn's checks.
Ensure SKL2CremeRegressor -> Creme2SKLRegressor is still a proper
estimator. Not ensured for classifiers at the moment due to discrepancy
in how classes are discovered (at first partial_fit for scikit-learn and
at __init__ for creme if prediction classes are to be consistent).
=> Add partial_fit to scikit-learn wrappers of creme estimators #267

creme/utils/__init__.py, creme/utils/vectordict.pyx
For #280.
Still WIP, implements a Cython `dict` wrapper that supports vector-like (as in element of a vector space) operations `+`, `-`, `*`, `/` and `@`. Should be useful in `glm` to store the weights, as a lot of dot products and arithmetic between weights and samples are made. Still need to add tests and integrate in code but maybe you can check if it fits the feature request.
Example of speedup and code readability improvement:
```python
>>> from creme.utils.math import dot
>>> x = {'a': 4, 'b': 2, 'c': 5}
>>> y = {'a': 3, 'b': 9, 'd': 4}
>>> %timeit dot(x, y)
993 ns ± 5.01 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
>>> from creme.utils import VectorDict
>>> vx = VectorDict(x)
>>> vy = VectorDict(y)
>>> assert vx @ vy == dot(x, y)
>>> %timeit vx @ vy
>>> %timeit vx @ …
```
=> WIP Cython dict wrapper supporting vector-like operations

creme/utils/__init__.py, creme/utils/data_conversion.py
Add two simple data conversion utility functions:
* `numpy2dict`: convert an one-dimensional numpy array to a dictionary
* `dict2numpy`: convert a dictionary containing only numerical data as its values to an one-dimensional numpy array
Note that the building process is being fixed in #319. Once this PR is merged, I should do a rebase to make sure everything is working as intended.
=> Add data conversion utilities

creme/utils/vectordict.pyx
As mentioned by @gbolmier the original implementation was faster so this PR adds an implementation for the case with neither factory nor masking.
It seems to mostly match the previous benchmark by @MaxHalford [#315 (comment)](https://github.com/creme-ml/creme/pull/315#issuecomment-656549424).
At the low end (size ~1) we get ~10x, at size ~100 and above we get ~3x (between the orange and blue lines).
Going significantly beyond that seems hard while keeping the data in Python dictionaries, which is needed to support arbitrary key / value types.
```py
from creme import utils
x = {i: i for i in range(2)}
xx = {i: i for i in range(100)}
xxx = {i: i for i in range(1_000)}
y = utils.VectorDict(x)
yy = utils.VectorDict(xx)
yyy = utils.VectorDict(xxx)
%timeit utils.math.dot(x, x)
%timeit y @ y …
```
=> New fast track for VectorDict dot product without mask

river/tree/_attribute_observer/numeric_attribute_class_observer_gaussian.py
Removes `sortedcontainers` dependency brought in #362 
The dependency was removed as functionality can be achieved with native options.
=> Fix unmet dependency issue in the tree module

docs/faq/faq.md, river/tree/_attribute_observer/numeric_attribute_class_observer_binary_tree.py, river/tree/_attribute_observer/numeric_attribute_regression_observer.py, river/tree/_base_tree.py, river/tree/_nodes/base.py, river/tree/_nodes/hatc_nodes.py, river/tree/_nodes/hatr_nodes.py, river/tree/hoeffding_tree_classifier.py, river/tree/hoeffding_tree_regressor.py
Fix #393.
---
- Protects Binary Search Tree-based attribute observers against the case where `None` is passed to trees' `learn_one`method and splits are attempted.
- It also makes the trees deal with the situation where a split feature's value is not found during the learning process.
---
Currently, the trees manipulate their branches by identifying them with integers. Why so? Well, this gives us a standardized way of dealing with numerical and categorical features. For instance, suppose a categorical feature carries a mixture of strings and numbers. If we identify the tree branches by their actual values, they will become a mess. Right?
Instead, we use increasing integer values starting from `0` till `n_branches - 1`. We also reserve negative values for special cases:
- `-1`: a branch …
=> Protect trees against missing feature values and missing labels

river/base/drift_detector.py, river/ensemble/adaptive_random_forest.py, river/ensemble/streaming_random_patches.py
This PR covers:
- Replacing `deepcopy()` with `clone()` in Streaming Random Patches and Adaptive Random Forest
- Making the `DriftDetector` class an extension of the `Base` class
Using `clone` in SRP and ARF simplifies the code. Thanks to the updates on the `_get_params` and `_set_params` in the `Base` class we can now use `**kwargs` in the ARF, decluttering the signature for this class. Now the ARF is consistent with the rest of the tree-based methods.
=> Propagate new Base class and the clone method

river/datasets/synth/__init__.py, river/datasets/synth/friedman.py, river/datasets/synth/mv.py, river/datasets/synth/planes_2d.py
Adds the following new regression synthetic data generators:
- FriedmanDrift, as described in this [paper](https://link.springer.com/article/10.1007/s10618-010-0201-y) (the one that introduces the well-known FIMT-DD tree regressor). It implements three variants of concept drift
- Planes2D (originally 2DPlanes)
- Mv
The last two generators are described in the [Luís Torgo](https://www.dcc.fc.up.pt/~ltorgo/Regression/DataSets.html) repository of regression datasets and were used in multiple research papers in the last years.
Moreover, this PR also modifies `river.synth.Friedman` by adding a gaussian noise to the label, as originally proposed in the [original paper](https://www.jstor.org/stable/2241837?seq=1).
=> Regression generators

README.md
The link to `online-ml.github.io` is broken, this PR updates it to redirect to the River API docs.
=> Fix broken link to API docs in README

.github/workflows/tests.yml, river/ensemble/streaming_random_patches.py, river/utils/estimator_checks.py
Following our discussion I decided to write a little test that checks that all of our class `__init__` signatures use immutable parameters.
=> Add check_init_params_are_not_mutable

river/ensemble/streaming_random_patches.py
This PR fixes a bug where the Streaming Random Patches classifier resulted in different behavior for different `numpy` versions. In newer numpy versions the `poisson` method provides different values (sampling) which resulted in internal models. 
For context, `numpy` made changes in the random number generation. From Numpy's [documentation](https://numpy.org/doc/stable/reference/random/index.html#quick-start):
> Call default_rng to get a new instance of a Generator, then call its methods to obtain samples from different distributions. By default, Generator uses bits provided by PCG64 which has better statistical properties than the legacy MT19937 used in RandomState.
For more information: [Legacy Random Generation](https://numpy.org/doc/stable/reference/random/legacy.html)
This seems to …
=> Enforce SRP reproducibility for different Numpy versions

river/ensemble/streaming_random_patches.py
Fix a typo in SRP's docs that makes the documentation build fail.
=> Fix docs build

river/compose/pipeline.py, river/compose/test_.py
As described in #499 it's not possible to predict without updating the scalers. This PR adds the `no_learn` parameter that avoids training the non-supervised parts.
I'm not sure this is the best solution so lets have a discussion on this.
Firstly without beeing a "clean code" zealot I still feel like adding binary arguments should generally be avoided in favour of separate methods with descriptive naming - is there no better name for the process of calculating a predictions while also updating weights than `predict_one`? Backwards compatibility notwithstanding. Or should we name the non-learning methods `predict_nolearn_one`, for example?
Secondly, if this is the proper solution - should it rather be named `learn` or `update_transformers` and default to true? As an added negation also …
=> Add no learn parameter to pipeline transformations

river/metrics/rolling.py, river/metrics/time_rolling.py, river/time_series/snarimax.py
Add a neat \_\_repr\_\_ for TimeRolling metric wrapper (see doctest)
Have been using it in my work for a while. 
I found it more readable than the current \_\_repr\_\_ for Rolling. If you like, I can align Rolling \_\_repr\_\_ for consistency.
=> implement neat repr for TimeRolling

river/drift/adwin.py
=> Recover the reset method in ADWIN that was lost during the refactoring.

river/tree/splitter/nominal_splitter_reg.py
=> [Fix] nominal features being split more than once in tree regressors

river/cluster/clustream.py, river/cluster/dbstream.py
This PR serves to handle `KeyError` cases at the beginning of each algorithm. 
Whenever the algorithm returns this error when `predict_one` is called, the index is automatically set to `0`, which comes from the assumption that all outlier points are kept in the same cluster.
=> Index fix for CluStream and DBStream

river/drift/hddm_a.py, river/drift/hddm_w.py
Currently, HDDM_W & HDDM_A drift detectors correctly detect a downward concept drift when two_side_option is set to True, however, the user is not notified of this detection.
For example, on this simple staircase-like pattern of probabilities (going up every 1k and then probability going down every 1k)
```python
l = []
for i in range(10):
if i <= 5:
l.append(np.random.choice([1, 0], p=[i/5, 1-i/5], size=1000))
else:
l.append(np.random.choice([1, 0], p=[(10-i)/5, 1-(10-i)/5], size=1000))
print(np.mean(l[-1]))
x = np.concatenate(l)
```
Probability of getting one every 1k steps:
```bash
0.0
0.189
0.395
0.598
0.81
1.0
0.812
0.621
0.394
0.21
```
The code from example only reports the upward drifts, even thou `two_sided_test` is explicitly set to True
```python
hddm_a = …
```
=> Make HDDM drift detectors report downward changes

docs/releases/unreleased.md, river/stats/iqr.py, river/stats/quantile.py, river/stats/test_.py
The title pretty much describes the purpose of this PR. It is related to #610.
Numpy provides multiple interpolation strategies. None of them match the previous version of `stats.RollingQuantile`.
This PR makes `stats.RollingQuantile` match the linear interpolation strategy (the default option). In the future, we might want to bring other options and add an `interpolation` parameter, as done in the most recent Numpy versions.
Here's a simple test using Numpy and River:
```python
import random
import numpy as np
from river import stats
rng = random.Random(42)
data = [rng.random() for _ in range(100)]
qs = [0., 0.01, 0.05, 0.1, 0.25, 0.5, 0.6, 0.75, 0.99, 1.]
np_percs = np.quantile(data, q=qs)
perc = {}
for q in qs:
perc[q] = stats.RollingQuantile(q=q, window_size=len(data))
for p in data: …
```
=> Make stats.RollingQuantile comply with np.quantile(interpolation="linear")

river/facto/hofm.py
To make the logic simpler and more performant
Use [numpy.multiply](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html) instead of for loop for `n_factors`.
Used [the example in the doc](https://riverml.xyz/latest/examples/matrix-factorization-for-recommender-systems-part-2/#higher-order-factorization-machines-hofm) and it reduced almost 30% of the time for the whole calculation.
Before:
```
[25,000] MAE: 0.761297, RMSE: 0.962054 – 0:00:52.080646 – 2.61 MB
[50,000] MAE: 0.751865, RMSE: 0.951499 – 0:01:44.105094 – 3.08 MB
[75,000] MAE: 0.750853, RMSE: 0.951526 – 0:02:36.503243 – 3.6 MB
[100,000] MAE: 0.750607, RMSE: 0.951982 – 0:03:27.302165 – 4.07 MB
```
After:
```
[25,000] MAE: 0.761297, RMSE: 0.962054 – 0:00:35.615119 – 2.61 MB
[50,000] MAE: 0.751865, RMSE: 0.951499 – …
```
=> [HOFM] Simplify the latent scalar calculation with numpy.multiply

docs/releases/unreleased.md, river/facto/base.py, river/facto/ffm.py, river/facto/fm.py, river/facto/fwfm.py, river/facto/hofm.py
To make it easy to check the contribution of each feature and each combination of features in an FM regressor.
1. [Refactor] Introduced common methods to calculate interactions
- `_calculate_interactions` is moved to `base`, which is calculated by:
- `_interaction_combination_keys`: combinations of interaction features (e.g. `sigma i < j` for normal FM)
- `_interaction_val`: value corresponding to a given combination of interaction features (e.g. `xi * xj` for normal FM)
- `_interaction_coefficient`: coefficient corresponding to a given combination of interaction features (e.g. `latents[xi] * latents[xj]` for normal FM)
1. Added `debug_one` and corresponding `doctest` to the following regressors:
1. Add `debug_one` in `base` using the common methds introduced above.
2. Added …
=> Add debug_one method to all FMRegressors

docs/javascripts/config.js
To fix broken equations for instant loading
example:
steps to reproduce
1. Open https://riverml.xyz/latest/api/facto/FFMClassifier/
2. Click on any link from the leftside navigation.
add the following lines to `docs/javascrpts/config.js` 
```javascript
document$.subscribe(() => {
MathJax.typesetPromise()
})
```
reference: https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math#configuration
Checked the fixed behavior in my local with `make livedoc`
=> docs: Enable to render equations for instant loading

setup.py
This pull request is dedicated to the discussion #815.  When the version of NumPy is < `1.2.0` we get an error `E ImportError: numpy.core.multiarray failed to import`. I edited the requirements so that the version of NumPy is >= `1.2.0` when installing river. ☀️
Here is the complete error when NumPy version is lower than `1.2.0`:
```sh
Traceback:
__init__.pxd:943: in numpy.import_array
???
E   RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
During handling of the above exception, another exception occurred:
../../../opt/miniconda3/envs/cherche/lib/python3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
cherche/retrieve/__init__.py:7: in <module>
from .tfidf import TfIdf …
```
=> Upgrade NumPy dependency version - ImportError

docs/releases/unreleased.md, river/rules/amrules.py, river/rules/base.py
The `repr` method from AMRules' rules only shows the literals. Even when we don't pass an instance for debugging purposed (as in `debug_one`) it is nice to have an idea of what the rules output.
This PR makes the regression rules show the target mean as the default consequent of a rule. `debug_one` was slightly updated to explicitly show the prediction strategy.
=> Make AMRules show a default rule consequent

docs/releases/unreleased.md, river/imblearn/__init__.py, river/imblearn/chebyshev.py
Implement the under-sampling and over-sampling methods for online regression described in in the following [paper](https://link.springer.com/article/10.1007/s10618-021-00793-1).
=> Add Chebyshev's inequality-based under- and over-sampling methods

river/cluster/denstream.py
Docstring fix for DenStream, including
- Update example in docstring to align with the parameters' feasible ranges.
- Check for the value of beta to be within the range `(0,1]`.
- Update docstring for `beta`, `mu` and reason for the implementation of `n_samples_init`.
This fix resolves the problems suggested in issue #874.
=> Docstring fix for DenStream

river/cluster/dbstream.py
I was going to open an issue, but figured this was a small enough change that it would be easier to open a pull request to both discuss and show what I mean! I was testing dbstream out more, and hit this case where the microcluster center couldn't update because of a key index error. This issue is a lot like the previous changes that we made to allow for updates only given the overlapping keys. So the solution of course is to add the "if j in x" to mapping of j to the new i center, and then you are allowed to have different keys without throwing an error.
Of course I'm doing this almost at 1am so no promises that my brain is working correctly :laughing:
=> dbstream: allow microcluster centoid update to have different terms

river/imblearn/chebyshev.py
This PR updates the Chebyshev regression samplers to match the original Java code and some extra details described in the original paper. 
I missed these details when only using the formulae to implement the sampling methods. These changes, although functional, do not change the current changelog and could be seen as bug fixes.
=> Update Chebyshev approaches

river/anomaly/filter.py
The anomaly_dector should be updated if we are not protecting the detector or if it is not an anomaly.  I.e. the only time it should not be updated is when we are protecting the detector and it is an anomaly.
=> Fix for protect_anomaly_detector logic

river/base/classifier.py, river/base/regressor.py, river/base/transformer.py
Before, on my laptop:
```sh
python -c "from river import stats"  0.91s user 0.22s system 268% cpu 0.419 total
```
Afterwards:
```sh
python -c "from river import stats"  0.36s user 0.09s system 263% cpu 0.174 total
```
I did specifically to make importing the `stats` module faster. There are many other places in the code base where we import pandas and scipy, so this doesn't have an impact in all modules. But it's a nice idea to have in mind.
=> Postpone pandas import in base module

river/utils/sorted_window.py
This pull request is an optimization for rolling methods.
When the window size reaches its maximum capacity to insert a new element, it is necessary to find the "oldest" element in the sorted list to delete it.
Usually, this search is done using a linear search with a complexity of o(n); however, in our case, the elements of the list are sorted, so it is possible to do a binary search o(log(n)). 
This optimization is a simple solution for large sliding windows https://github.com/online-ml/river/issues/906.
=> Optimized append sorted window

docs/overrides/home.html, docs/releases/unreleased.md, river/time_series/__init__.py, river/time_series/evaluate.py, river/time_series/metrics.py, river/time_series/test_evaluate.py
This is handy for being able to compare forecasting models. Indeed it's not as clear-cut to compare forecasting models if we only have `HorizonMetric` in our toolbox.
Hey @dberardo-com, could you let me know what you think?
=> Implement average forecast metric

river/preprocessing/scale.py
Sometimes `stats.EWVar` can output negative values due to numeric imprecision. The underlying variance formulae are known to be unstable and sometimes called the "naive" approach in textbooks. For the time being, we don't have a version leveraging the Welford algorithm.
This PR protects `preprocessing.AdaptiveStandardScaler` against the numerical instability of EWVar.
=> Protect AdaptiveStandardScaler against numerical inconsistencies

river/feature_extraction/agg.py
While running the bike-sharing forecasting example, I discovered a bug. `TargetAgg` is treated as an unsupervised transformer. By swapping the inheritance order the issue is solved.
=> Ensure TargetAgg is treat as supervised

.github/workflows/pypi.yml
See https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0
=> Add Python 3.11 to list of built wheels

docs/releases/unreleased.md, river/feature_extraction/test_vectorize.py, river/feature_extraction/vectorize.py
cc @Dennis1989
Ok so there's now a `stop_words` parameter in `BagOfWords` and `TFIDF`. I also took the liberty of adding a `tokenizer_pattern` to override the default parameter. Finally, I've made sure the processing steps work on token generators, rather than lists. That should be helpful for longish texts. Oh and now there's some unit tests.
=> Add stop_words parameter

docs/releases/unreleased.md, river/compose/union.py, river/feature_extraction/agg.py
The rendering of the `Agg.state` property was malformed in the docs. I moved the example. I also noticed that we couldn't access `TransformerUnion` steps by positional index, so I changed that too.
=> Fix agg state doc

river/cluster/clustream.py
This new implementation of CluStream serves two purposes:
- One, this version is a refactor of the previous one with certain improvements, such as shortening variable names, removing redundant portions/loops and ensuring that private parts can not be accessed by users.
- Two, this implementation is an improvement of the original version by using Welford's algorithm to calculate the incremental variance of the data points and time stamps instead of having to save the number of observations, linear sum and sum of squares as per the traditional convention. This is facilitated through `stats.Var` within `River`.
=> Refactor code and use Welford's algorithm to CluStream

.github/workflows/pypi.yml
The GitHub action worked, but the syntax was not good; now, it's cleaner.
=> Fix syntax pypi.yaml

river/drift/ddm.py, river/drift/test_drift_detectors.py
Consider a data stream with only ones and no zeros. When the code block inside `if n > self.warm_start:` in method `river.drift.DDM.update` is entered the first time, `p_i`, `s_i`, `self._p_min`, `self._s_min` will be 1.0, 0.0, 1.0, 0.0 respectively, then `p_i + s_i >= self._p_min + self.drift_threshold * self._s_min` will hold and a drift will be reported. I fix this bug by replacing `>=` with `>` and add the corrosponding testcase to `river/drift/test_drift_detectors.py`.
=> Fix bug that DDM reports drift on data stream with only ones

river/multioutput/chain.py
Hi:
I'm working in multi-label stream learning using this nice library and I've found a slight bug –I think–, in the `prediction_proba_one` method of `ClassifierChain`. Specifically, in the part of storing the probabilities of the prediction for the next labels, the iteration is made at *labelset level*, so the probabilities are saved in a sub-dictionary of the instance. This makes the base classifier fails or, in the best-case scenario, ignore the previous probabilities in prediction time. You can check it with the following code:
```
import itertools
from river.datasets import Music
from river.multioutput import ClassifierChain
from river.neighbors import KNNClassifier
stream = Music().take(20)
model = ClassifierChain(KNNClassifier())
for x, y in itertools.islice(stream, 19): …
```
=> Fixed access to previous predictions in CC

river/metrics/report.py
We can't cast to int because the support can be a decimal when sample weights are used. Using `.rstrip` correctly is the answer. I checked and this is the only place we used it incorrectly.
Closes #1068
=> fix rstrip in clf report support

docs/recipes/.pages, docs/recipes/bandits-101.ipynb, docs/recipes/rolling-computations.ipynb, river/bandit/base.py, river/bandit/envs/__init__.py, river/bandit/envs/candy_cane.py, river/bandit/envs/test_bed.py, river/bandit/envs/testbed.py, river/bandit/epsilon_greedy.py, river/bandit/evaluate.py, river/bandit/ucb.py, river/model_selection/bandit.py
- Added the k-armed testbed from Sutton and Barto
- Fixed an issue where the `evaluate` function didn't update the policies
- Fixed an issue with the epsilon greedy strategy, it wasn't working correctly
- Added a recipe to showcase how to use bandits; reproduced the charts from Sutton and Barto
=> Bandits bandits bandits

docs/releases/unreleased.md, river/base/base.py, river/base/test_base.py
@XaviMartiCamarasa stumbled on a bug in #1097. He tried to clone a `SNARIMAX`. The latter's `regressor` parameter was a pipeline. The bug is that cloning the `SNARIMAX` doesn't work because cloning a `Pipeline` nested in an estimator doesn't work. This pull request fixes that. Thankfully, I didn't have to make the code more complex. In fact, it's simpler now :)
=> Nested pipeline cloning

river/multiclass/occ.py
line 59 missing reference to imported library multiclass
=> fixed typo in file OCC.py

docs/releases/unreleased.md, river/multiclass/occ.py, river/stream/shuffling.py
@Yasmen-Wahba I found the issue to #1116. The problem was that the list of all possible codes were generated in memory and then sampled from. This takes too memory when the code size is big, say 30. I added a way to choose what code sampling method to use. The `'random'` method is what scikit-learn does, while the `'exact'` method is what we did before.
=> Add coding_method parameter to OCC

river/anomaly/filter.py, river/anomaly/hst.py, river/anomaly/test_hst.py, river/checks/__init__.py, river/checks/anomaly.py, river/checks/common.py, river/compose/pipeline.py, river/test_estimators.py
`checks.check_estimator` will now run a test suite for anomaly detectors. I got one bug doing this: the half-space trees implementation was sensitive to the feature order.
=> Add systematic tests for anomaly detectors

.gitignore, docs/releases/unreleased.md, river/base/__init__.py, river/base/drift_detector.py, river/drift/adwin.py, river/drift/ddm.py, river/drift/eddm.py, river/drift/hddm_a.py, river/drift/hddm_w.py, river/drift/kswin.py, river/drift/page_hinkley.py, river/drift/periodic_trigger.py, river/drift/retrain.py
Some drift detectors have a `warning_detected` property, some don't. I believe introducing a new base class clarifies this difference.
=> Introduce base.DriftAndWarningDetector

.github/workflows/unit-tests.yml, docs/releases/unreleased.md, river/multioutput/__init__.py, river/multioutput/chain.py, river/multioutput/encoder.py
Hey @smastelini! I believe there is a little mistake in `MultiClassEncoder`. Basically, it seems to me that the predicted outputs are always 1 or 0 for each `False/True` of each output. That's because a probability is assigned to `True` or `False`, which is then converted to `1` or `0` with `utils.norm.normalize_values_in_dict`. This is difficult to notice because the metrics we use don't care about the probabilties. I think the implementation I suggest is correct, but I'll let you double check.
Anyway, good work! It's a nice model to have.
=> Handle probabilities in MultiClassEncoder

river/forest/aggregated_mondrian_forest.py, river/tree/mondrian/mondrian_tree.py, river/tree/mondrian/mondrian_tree_classifier.py, river/tree/mondrian/mondrian_tree_nodes.py
- Ok I just removed the `n_classes` and added some documentation to `dirichlet`. Honestly I think this is more than fine for now.
- I also tidied up the code a tiny bit.
=> Remove n_classes parameter in Mondrian trees

river/metrics/efficient_rollingrocauc/efficient_rollingrocauc.pyx, setup.py
Make the flag `-std=c++11` on `efficient_rollingrocauc.pyx` explicit to avoid errors on compiling on macOS.
=> Fix RollingROCAUC Cython build on macOS

river/cluster/textclust.py
ClusterId can be out of scope if "there is nothing to process"
=> ClusterId out of scope

docs/releases/unreleased.md, river/drift/retrain.py, river/forest/adaptive_random_forest.py, river/tree/extremely_fast_decision_tree.py, river/tree/hoeffding_adaptive_tree_classifier.py, river/tree/hoeffding_tree_classifier.py, river/tree/nodes/efdtc_nodes.py, river/tree/nodes/htc_nodes.py, river/tree/split_criterion/gini_split_criterion.py, river/tree/split_criterion/hellinger_distance_criterion.py, river/tree/split_criterion/info_gain_split_criterion.py
Fixes #1169.
I added the `max_share_to_split` parameter, as discussed in the issue. Besides that, I also exposed another parameter that was inherited from MOA. This one prevents splitting when most of the data is concentrated in a single branch (regardless of the class distribution).
=> New parameters for Hoeffding Tree Classifiers

river/preprocessing/ordinal.py
The idea:
Ordinal encoder for categoricals that robustly accomodates for:
- unfamilliar category values
- empty category values
Achieved by:
- using only positive integers for encoding (no custom mappings like in `sklearn` implementation)
- reserving two first values for unknown and empty category values
Note:
- positive-only indexing is useful when passing output to some tensor-based modeling frameworks which require indexing tensors and don't have flexible indexing things like `VectorDict` (i'm mixing `river` with jax-based PPL for online Bayesian modeling, proper `OrdinalEncoder` is very valuable)
- naturally i have included mini-batch implementation aswell
Example tests:
```python
transformer = OrdinalEncoder()
X = [
{"country": "France", "place": "Taco Bell"},
{"country": None, …
```
=> [WIP] Feature/ online ordinal encoder

docs/releases/unreleased.md, river/forest/__init__.py, river/forest/aggregated_mondrian_forest.py, river/preprocessing/ordinal.py, river/tree/mondrian/__init__.py, river/tree/mondrian/mondrian_tree.py, river/tree/mondrian/mondrian_tree_classifier.py, river/tree/mondrian/mondrian_tree_nodes.py, river/tree/mondrian/mondrian_tree_regressor.py, river/utils/random.py
Thanks to a comment in the Fellowship of Online Machine's discord, I was able to track a bug affecting both the classifier and regression versions of AMF.
In my preliminary tests, the predictive performance improved in both cases. @kenzabenjelloun, thanks for your work on the AMFRegressor. I think the bug you mentioned in the previous PR might have been fixed :D
=> Fix bug in AMFClassifier and finish AMFRegressor (#1166)

river/metrics/multioutput/__init__.py, river/metrics/multioutput/accuracy_moa_jaccard.py
This metric is interesting because it works fully with any multi-label dataset, and avoids possible result bias that can be seen with the Macro or Micro Average wrappers on metrics like the Accuracy when some labels are rarely used.
We thought that this metric would be interesting for anyone doing multi-label classification, and also for anyone coming from the MOA platform as it is one of the metrics found there that was missing in River.
=> Added Jaccard Accuracy (also found in MOA)

docs/releases/unreleased.md, river/anomaly/gaussian.py, river/proba/__init__.py, river/proba/base.py, river/proba/gaussian.py
Implemented MultivariateGaussian, as part of ContinuousDistributions, taking advantage of EmpiricalCovariance class, extending its example in doctest, showing basic usage of the class.
=> Add MultivariateGaussian

docs/releases/unreleased.md, river/compose/product.py, river/naive_bayes/bernoulli.py
This should fix the unit tests on `main`.
=> Support pandas v2

docs/releases/unreleased.md, river/base/drift_detector.py, river/forest/adaptive_random_forest.py, river/forest/online_extra_trees.py
While reviewing #1309 I realized that the proposed changes would make the existing code problematic due to the existing class hierarchy. For instance, MSTS is intended for classification tasks, but the ARFRegressor ended up being affected to some extent.
Thus, I decided to first simplify the existing code. Next, we need to think about how to better integrate MSTS.
Suggestions:
- Create a new base Class intended to select subsets of classifiers/regressors in forest-based ensembles to generate the responses. This should become a single new parameter to ARF rather than multiple ones (ARF after #1309 would have over 30 parameters!). Such implementation must be generic and work separately from the main ARF logic (or any other target ensemble algorithm).
- In such case, such selector would be …
=> Simplify Adaptive Random Forest

docs/releases/unreleased.md, river/covariance/emp.py, river/proba/gaussian.py
Hey there 👋
I was thinking about adding _from_state method to [MultivariateGaussian](https://github.com/online-ml/river/commit/e767f26692ac8bf4cae9d38bfacfa97080cf5f49) and [EmpiricalCovariance](https://github.com/online-ml/river/commit/be0b3257b579dc7401608d5dda1106e1bdf92cc2). 
I believe it might aid the versatility of the classes usage. Nevertheless, I must admit that it might be little tricky for some users to retrieve covariance as dictionary of correct form.
Here is a pull request with proposed changes! (Did not open discussion as I considered this quite minor, sorry for inconvenience)
Please let me know what you think.
Thank you 🙏
=> Add _from_state methods to MultivariateGaussian and EmpiricalCovariance

docs/releases/unreleased.md, river/cluster/dbstream.py
This PR fixes multiple issues proposed in issue #1324 by @donny741, with the following changes:
- Addition of the `-` sign before the `fading_factor` in accordance with the algorithm 2 proposed by Hashler and Bolanos to allow clusters with low weights to be removed.
- The new `micro_cluster` is added with the key derived from the maximum key of the existing micro clusters. If the set of micro clusters is still empty (`len = 0`), a new micro cluster is added with key `0`.
- `cluster_is_up_to_date` is set to `True` at the end of the `self._recluster()` function.
=> DBSTREAM fix (related to issue #1324)

docs/releases/unreleased.md, river/ensemble/streaming_random_patches.py, river/tree/extremely_fast_decision_tree.py, river/tree/splitter/nominal_splitter_classif.py
This was a rather cryptic bug that was really difficult to track down.
Thank you @FedericoMz for providing the reproducible example, I would never find the culprit without that.
In the end, the problem was not in EFDT but in the splitter used in nominal attributes. It previously used `collection.defaultdict` objects in an attempt to simplify and speed up the code. 
However, during prediction actions (such as `predict_proba_one` and `debug_one`) if the `collection.defaultdict` in the splitter was checked for the existence of a previously non-observed branch, the missing value would be inadvertently created.
This created a mismatch between the number of existing and tracked tree branches.
This bug could potentially affect other trees, but was really hard to come by.
=> Fixes #1248

docs/releases/unreleased.md, river/cluster/dbstream.py
When the timestamp is set to 0 it may result in the immediate removal of the density graph entry because during cleanup 0 will be used as a current timestamp and the fading value will be incorrect ([here](https://github.com/online-ml/river/blob/main/river/cluster/dbstream.py#L276))
=> DBSTREAM: fix density graph timestamps

docs/releases/unreleased.md, river/cluster/dbstream.py, river/cluster/test_dbstream.py
Neighbors of neighbors are not added to the `seed_set` so they receive different labels even though they have adjacent clusters.
Fixing by changing the `if` statement so neighbors without labels are appended to the `seed_set` and then assigned the label in following iterations.
=> DBSTREAM: fix microcluster labeling

docs/releases/unreleased.md, river/cluster/dbstream.py, river/cluster/test_dbstream.py
It is possible for the microcluster (`mc`) to be removed, but for the shared density graph entry (`Sij`) associated with that microcluster to remain because:
- The threshold for removing `Sij` is `α` (a.k.a. `intersection_factor`) times lower than the threshold for removing a `mc`;
- and no mechanism would ensure the removal of associated `Sij` when `mc` is removed.
This introduces a `KeyError` during the `weighted_adjacency_matrix` building step when looking up removed `mc`. Adding a `try` block to account for that
=> dbstream: fix adjacency matrix building

docs/releases/unreleased.md, river/drift/__init__.py, river/drift/no_drift.py, river/forest/adaptive_random_forest.py
This PR addresses #1332 by adding the `drift.NoDrift` class. This detector does nothing and can be used to bypass the concept drift handling capabilities in ARF.
=> Add the NoDrift dummy drift detector

docs/releases/unreleased.md, river/anomaly/__init__.py, river/anomaly/sad.py, river/test_estimators.py
This PR contains the implementation of the Standard Absolute Deviation (SAD) anomaly detection algorithm.
This implementation is adapted from the implementation within [PySAD](https://github.com/selimfirat/pysad/blob/master/pysad/models/standard_absolute_deviation.py) (Python Streaming Anomaly Detection) package, which calculates the anomaly score by dividing the deviation from the mean/median to the standard deviation of all points seen within the data stream. This idea is adapted from the paper by [Hochenbaum et al. (2017)](https://doi.org/10.48550/ARXIV.1704.07706).
Despite being a fairly simple algorithm, the implementation of this algorithm allows the `anomaly` submodule of `River` to have a solid competitor to conduct any benchmarking work.
There is no unit test for this algorithm …
=> Implementation of the StandardAbsoluteDeviation (SAD) anomaly detection algorithm

docs/.pages, docs/license/.pages, docs/license/license.md
This PR adds a license tab to the River docs. By clearly displaying that River is under the 3-clause BSD license visitors will be able to quickly understand River's licensing terms.
=> Add license to riverml.xyz

mkdocs.yml
As I was going through the documentation I noticed something was off in the rendering of the [getting-started/concept-drift-detection](https://riverml.xyz/latest/introduction/getting-started/concept-drift-detection) section.
By opening the source code it was clear that latex is not rendering properly.
The issue gets fixed by pinning the minor version of mathjax.
- **Live** and local with https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
- Local with https://cdn.jsdelivr.net/npm/mathjax@3.2/es5/tex-mml-chtml.js
=> docs: pin mathjax minor version

Cargo.toml
Following #1563, PyO3 is upgraded to resolve a crash in the test suite that appeared after Rust 1.78 was released.
=> Fix a Rust panic in the tests

.github/actions/install-env/action.yml, .github/workflows/release-docs.yml
- Update actions to latest versions
- Update Python version to 3.12.3 in release-docs workflow
- Increment Poetry installation cached key in install-env workflow
=> Update install-env and release-docs workflows

river/metrics/roc_auc.py
SciPy deprecated `scipy.integrate.trapz` long ago and it had instead
been renamed to `scipy.integrate.trapezoid`. The `ROCAUC()` class uses
the former instead of the latter (causing an `AttributeError`), with
the latter being included from the start of SciPy version 1.6.0 (start
of 2021). This is a small fix: I've added a simple `hasattr()` check for 
compatibility with versions that still have `scipy.integrate.trapz` and
to use it if it's there over `scipy.integrate.trapezoid`, but it might be
unnecessary, since those versions are outdated.
https://docs.scipy.org/doc/scipy/release/1.6.0-notes.html#scipy-integrate-improvements
=> Fixed `AttributeError` in metrics/roc_auc.py.

poetry.lock, pyproject.toml, river/bandit/bayes_ucb.py, river/bandit/envs/__init__.py, river/bandit/envs/candy_cane.py, river/bandit/envs/testbed.py, river/bandit/epsilon_greedy.py, river/bandit/evaluate.py, river/bandit/exp3.py, river/bandit/random.py, river/bandit/test_envs.py, river/bandit/test_policies.py, river/bandit/thompson.py, river/bandit/ucb.py
The maintainers of OpenAI's Gym decided to stop maintaining the library and moved over to a fork called Gymnasium.
They advise switching to the new library, which can be used as a drop-in replacement.
I used this opportunity to upgrade the library to the latest stable version (from 0.26 to 0.29).
See: https://github.com/openai/gym/blob/master/README.md
Closes #1579
=> Replace Gym with Gymnasium

river/base/drift_detector.py, river/drift/kswin.py, river/forest/aggregated_mondrian_forest.py, river/tree/nodes/hatc_nodes.py, river/tree/nodes/sgt_nodes.py, river/tree/stochastic_gradient_tree.py
When type checking the code, MyPy raises some warnings:
```
river/drift/kswin.py:112: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
river/tree/nodes/sgt_nodes.py:45: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
river/tree/nodes/hatc_nodes.py:140: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
river/tree/stochastic_gradient_tree.py:56: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
river/forest/aggregated_mondrian_forest.py:173: note: By default the bodies of untyped functions …
```
=> Clear out MyPy's warnings

docs/releases/unreleased.md, river/forest/adaptive_random_forest.py, river/forest/online_extra_trees.py, river/stream/twitch_chat_stream.py, river/tree/extremely_fast_decision_tree.py, river/tree/hoeffding_adaptive_tree_classifier.py, river/tree/hoeffding_adaptive_tree_regressor.py, river/tree/hoeffding_tree.py, river/tree/hoeffding_tree_classifier.py, river/tree/hoeffding_tree_regressor.py, river/tree/isoup_tree_regressor.py, river/tree/utils.py, river/utils/pretty.py
Where unit multiples of the byte are used, this PR uses the unambiguous name of the unit.
Binary units have a different symbol (KiB, MiB) to distinguish them from the general-use decimal units (kB, MB). River only uses the binary units.
The only functional change is in `tree.utils.calculate_object_size`, where the recognised valued for the second (optional) argument were changed. This optional argument was not used in River.
Closes #1582
=> Use units based on powers of 2

docs/releases/unreleased.md, river/forest/adaptive_random_forest.py, river/tree/extremely_fast_decision_tree.py, river/tree/hoeffding_adaptive_tree_classifier.py, river/tree/hoeffding_adaptive_tree_regressor.py, river/tree/hoeffding_tree.py, river/tree/hoeffding_tree_classifier.py, river/tree/hoeffding_tree_regressor.py, river/tree/isoup_tree_regressor.py, river/tree/stochastic_gradient_tree.py
Python's recursion limit is obtained with `sys.getrecursionlimit()`. In this PR, trees will stop at 20 before the limit, to ensure the calling program has enough headroom.
How many "steps" before the limit should be kept (here 20) is open to discussion.
Fixes #1578
=> Limit tree growth to the system recursion limit

river/conftest.py, river/test_estimators.py
There were still lingering references to deleted modules from `river/compat`.
Closes #1587
=> Remove mention of former compat modules

mkdocs.yml
The domain polyfill.io was taken over by a malicious actor to download malware.
Polyfill is not needed for modern browsers.
It is recommended to remove references to the website.
Closes: #1589
=> Remove script download from polyfill.io

river/stats/iqr.py
This fixes #1602 with the same method, as in the other quantlie related stats modules.
=> Add Hack for stats.IQR get method to avoid panicking

pyproject.toml, river/bandit/envs/__init__.py
As discussed in #1592, this PR enables MyPy's strict mode by default for the repository.
Since none of the modules are fully annotated yet, they have an override to disable the extra rules.
Because MyPy has [a configuration bug](https://github.com/python/mypy/issues/11401), the settings enabled by the strict mode need to be disabled individually.
Only the options that raised new errors are disabled in the override : this means that MyPy will now perform more checks over the code.
=> New MyPy configuration for per-module type completeness

docs/releases/unreleased.md, river/feature_extraction/vectorize.py
`feature _extraction.TFIDF` has no explicit implementation of the mini-batch methods `learn_many` and `transform_many`, meaning that Python will fall back on the ones provided by its parent `feature _extraction.BagOfWords`. This causes TF-IDF to have a different behaviour in single-instance and in mini-batch mode.
This PR is a band-aid that adds the methods for TF-IDF to make it explicit they are not supported. Both will raise an exception when called.
A true mini-batch version could be added at a later point.
Fixes #1629
=> Make mini-batch TF-IDF raise an exception

river/bandit/bayes_ucb.py, river/covariance/test_emp.py, river/naive_bayes/bernoulli.py, river/utils/test_rolling.py
River's test suite raises an important quantity of warnings, and their number may hide defects in new code. Most warnings are created by a few pieces of code run many times. This PR aims to greatly reduce the number of warnings in the tests.
Before: 209139 warnings
After : 17 warnings
Most warnings left are caused by libraries like NumPy and Scikit-learn.
Four of the remaining warnings are a deprecation : `pickle`, `copy`, and `deepcopy` support will be removed from `itertools` in Python 3.14. *This may warrant an action.*
This PR also fixes a semi-bug: 
In [`naives_bayes.BernoulliNB.joint_log_likelihood_many()`](https://github.com/online-ml/river/blob/main/river/naive_bayes/bernoulli.py#L266), the `if hasattr(X, "sparse")` path was never used (at least in the tests) because sparse …
=> Fix tests warnings

.github/workflows/code-quality.yml, .github/workflows/dev-docs.yml, .github/workflows/pypi.yml, .github/workflows/release-docs.yml, .github/workflows/unit-tests.yml, README.md, docs/releases/unreleased.md, poetry.lock, pyproject.toml
- Drop support for 3.9
- Add support for 3.13
- Fix unit-tests workflow to use matrix for Python versions
Recent [`PyO3=0.23.0`](https://github.com/PyO3/pyo3/releases/tag/v0.23.0) release added support for python 3.13 but bumping it to `0.23.1` leads to `rust_src` compilation errors (cc @AdilZouitine).
CI builds river and run unit-tests successfully with the current `PyO3=0.18.3` so it should be fine to merge as it is.
=> Support Python 3.10 to 3.13

Cargo.toml, rust_src/lib.rs
Hey @agriyakhetarpal,
with @gbolmier we tried to bumb Py03 version from 0.18.0 to 0.23.1
=> Bump  PyO3 from 0.18.3 to 0.23.1

pyproject.toml
River did not mention its licence in the metadata, causing PyPi to have no information about it.
This new line will enable Poetry to add licence information when building a wheel.
=> Add the licence in the project metadata

river/checks/__init__.py, river/checks/common.py, river/compat/sklearn_to_river.py, river/ensemble/streaming_random_patches.py
This new test is similar to [the existing](https://github.com/online-ml/river/blob/d59f78881116180a788eee69c7a51e4fc91df6f7/river/checks/common.py#L94) `check_disappearing_features`, but tests the case where only one feature is left.
Such a situation can happen when one uses aggressive feature reduction preprocessing.
It tests for the case encountered in #1560, and discovered a similar problem in SRPClassifier (fixed in the PR).
=> Add a stricter test for feature elimination

.pre-commit-config.yaml
The tool versions listed for pre-commit were different from the ones in `poetry.lock`, leading to different behaviour between a local invocation and from pre-commit.
In the case of MyPy, pre-commit's version was severely outdated, causing false positives and false negatives.
When River's dependencies are updated, pre-commit's configuration should be updated to have the same versions.
I realise now that this is one of the causes of #1665; but this PR does not solve the main problem of dependencies between files anyway.
=> Sync pre-commit's repo versions with Poetry

docs/releases/0.22.0.md, river/feature_selection/k_best.py
This PR is related to Issue #1680
- Add `use_abs` parameter to `SelectKBest` for absolute similarity 
- Add docstring test for `use_abs` parameter
`SelectKBest` transformer currently ranks features based on raw Pearson correlation values [-1,1]. So features that are negatively correlated with the target might be excluded, even if they are highly predictive.
e.g:
0.8 → ranked high
−0.9 → ranked low or excluded, despite being stronger
- A new `use_abs` parameter has been added to the `SelectKBest` constructor. When set to `True`, the selector ranks features based on the absolute value of their similarity scores. (Default is `False` so it won't break client code)
- The leaderboard logic inside `learn_one` method has been modified to respect the `use_abs` value while ranking.
- The docstring …
=> Add use_abs parameter to SelectKBest

CONTRIBUTING.md
As @gbolmier indicated (https://github.com/online-ml/river/discussions/1699#discussioncomment-13812311), River now uses the NumPy-style docstrings everywhere, but the guidelines were still referencing the former convention.
This PR also removes mention of yamp: installing it is not necessary any more to build the docs, as the Markdown parser is now shipped with River (standalone yamp is deprecated).
=> Update the contributing guidelines for docstrings

river/stats/pearson.py
For some reason, the `update_many` method was not available on PearsonCorr when it was trivial to do.
=> Add the update_many method to PearsonCorr.
