- creme/stats/__init__.py
- creme/stats/_sorted_window.py
- creme/stats/quantile.py
- creme/stats/rolling_max.py
- creme/stats/rolling_min.py
- creme/stats/rolling_mode.py
- docs/api.rst
Test passed.
Rolling min and max use private sorted window class.
> Rolling windowed min and max

- creme/stats/__init__.py
- creme/stats/rolling_sem.py
- creme/stats/sem.py
- docs/api.rst
These two statistics have been validated. The results are the same as those of https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html
> New feature: standard error of the mean, incremental and rolling incremental sem

- .gitignore
- creme/stats/ewvar.py
I'm adding this here now because the `dev` branch is missing?
> Exponential Smoothing

- README.md
The CONTRIBUTING.md was broken (because of backticks in link).
> Fix CONTRIBUTING.md link

- CHANGELOG.md
- creme/stats/__init__.py
- creme/stats/iqr.py
- docs/stats.rst
I have implemented IQR and RollingIQR, don't hesitate to tell me the modifications to make.
> Add IQR and RollingIQR

- creme/reco/normal.py
- creme/reco/svd.py
Update SVD module  to handle initializers. Fix a typo in normal predictor and add test to it.
> Update reco module

- creme/model_selection/score.py
- docs/faq.rst
- setup.py
Fix progressive_val_score, modify FAQ with differences between sklearn and creme and remove torch from dependencies
> Fix progressive_val_score function

- creme/linear_model/glm.py
- creme/optim/sgd.py
- creme/utils/test_vectordict.py
- creme/utils/vectordict.pyx
For #280.
Added tests for `VectorDict` and features necessary to its use in `GLM`.
> [MRG] Use VectorDict to store weights in GLM

- creme/utils/test_vectordict.py
- creme/utils/vectordict.pyx
`*` and `/` between two VectorDict
`abs`, `min`, `max`, `minimum`, `maximum`
Uses union of of keys for now in `*` and `/`, see discussion in #280.
> Add several operations to VectorDict

- creme/facto/base.py
- creme/facto/ffm.py
- creme/facto/fm.py
- creme/facto/fwfm.py
- creme/facto/hofm.py
- creme/reco/baseline.py
- creme/reco/biased_mf.py
- creme/reco/funk_mf.py
- creme/reco/normal.py
- docs/examples/matrix-factorization-for-recommender-systems-part-1.ipynb
- docs/examples/matrix-factorization-for-recommender-systems-part-2.ipynb
- docs/examples/matrix-factorization-for-recommender-systems-part-3.ipynb
#325 was reverted by #328 due to an error in #327. Fix this mess, sorry for the inconvenience :)
> [MRG] Facto module clean up and add MF example part 2 and init part 3

- river/ensemble/__init__.py
- river/ensemble/bagging.py
This PR includes two bagging methods:
- `ADWINBagging`
- `LeveragingBagging`
> ADWINBagging and LeveragingBagging

- creme/multiclass/ovr.py
> Fix bug in OneVsRestClassifier

- river/metrics/__init__.py
- river/metrics/balanced_accuracy.py
- river/metrics/base.py
I also need to figure out how to use `correction` in `BalancedAccuracy` so as to make the metric similar to `adjusted` in `scikit-learn`.
> adds balanced accuracy score

- river/datasets/synth/agrawal.py
- river/datasets/synth/anomaly_sine.py
- river/datasets/synth/concept_drift_stream.py
- river/datasets/synth/hyper_plane.py
- river/datasets/synth/led.py
- river/datasets/synth/logical.py
- river/datasets/synth/mixed.py
- river/datasets/synth/random_rbf.py
- river/datasets/synth/sea.py
- river/datasets/synth/sine.py
- river/datasets/synth/stagger.py
- river/drift/adwin.py
- river/drift/ddm.py
- river/drift/eddm.py
- river/drift/hddm_a.py
- river/drift/hddm_w.py
- river/ensemble/adaptive_random_forest.py
- Improved/reworded some docstrings for clarity.
- Fixed minor issues in docstrings that resulted in them not being rendered properly in the documentation.
- Hide internal methods in the STAGGER generator.
> Misc minor improvements

- river/metrics/__init__.py
- river/metrics/_performance_evaluator.py
- river/metrics/r2.py
- river/metrics/test_.py
This PR includes the implementation of the R^2 score (coefficient of determination) for regression tasks.
> Add the coefficient of determination  (R^2) metric for regression

- river/tree/_tree_utils.py
> Fix error in Hoeffding Trees when instances are missing some of their features

- README.md
@online-ml/devs can you thing of any other companies?
> Add company logos

- river/preprocessing/__init__.py
- river/preprocessing/scale.py
- river/stats/ewvar.py
This uses an exponentially weighted moving average and variance to scale the data. Initially I was going to add an `alpha` parameter to `StandardScaler` and use some `if`s  but it looked really ugly, so I created a separate class, which I think is fine.
> Add AdaptiveStandardScaler

- .github/workflows/tests.yml
- river/anomaly/hst.py
- river/anomaly/test_hst.py
- river/datasets/synth/concept_drift_stream.py
- river/datasets/test_datasets.py
- river/expert/bandit.py
- river/metrics/test_.py
- river/neighbors/sam_knn.py
> Use the most populated child branch in half-space trees when a feature is missing

- river/compose/test_.py
Add coverage for testing of `learn_unsupervised` in `compose.Pipeline`
> Parametrize tests for proba-methods

- README.md
> Update README: redirect users to the discussion tab

- river/stats/base.py
> Fix repr of stats.Univariate-related classes

- river/utils/skmultiflow_utils.py
> correct rounding for 0.0

- river/neighbors/base_neighbors.py
Classification probabilities were not being wrapped with the softmax
function.
> Fix issue with KNNClassifier

- river/linear_model/softmax.py
- river/test_.py
Following [this](https://github.com/online-ml/river/discussions/549) discussion.
> Remove SoftmaxRegression from blacklist

- README.md
- docs/getting-started/installation.md
A PR updating doc and readme to show how to install river using pip.
> pip install river 😎

- river/anomaly/hst.py
- river/drift/hddm_w.py
- river/feature_extraction/vectorize.py
- river/metrics/_performance_evaluator.py
- river/stats/quantile.py
- river/tree/base.py
- river/tree/test_base.py
- river/utils/histogram.py
I actually didn't manage to find enough time to decently work on tree viz. I did a couple of light improvements. In particular, I added the `to_dataframe` method, which I think we should use in favor of `model_description`.
The way I see it, we have 3 options for tree viz:
- Keep using graphviz: it's ugly but it works.
- Write an HTML viz. It could be pretty and interactive but I need to spend time on it.
- Integrate with [dtreeviz](https://github.com/parrt/dtreeviz), which looks good but is a bit akward because you need to pass around the data along with the model.
> Tree improvements

- river/base/base.py
Replace the recursive utility to avoid problems with recursion limits.
> Measure memory usage iteratively

- river/drift/ddm.py
- river/drift/page_hinkley.py
- river/drift/test_drift_detectors.py
Update the implementation of DDM and Page-HinckleyDM to follow the description in their paper respectively.
> Update the implementation of DDM and Page-HinckleyDM

- docs/releases/0.7.0.md
- docs/releases/0.7.1.md
- river/anomaly/hst.py
- river/compose/pipeline.py
- river/compose/viz.py
- river/stream/iter_csv.py
- river/stream/test_iter_csv.py
- river/tree/base.py
- river/tree/test_base.py
- river/tree/viz.py
> Handle empty fields in iter csv

- river/ensemble/adaptive_random_forest.py
> Protect ARFReg against AttributeError

- docs/faq/faq.md
- river/base/classifier.py
- river/naive_bayes/base.py
- river/naive_bayes/gaussian.py
> Fix classifier methods

- docs/releases/unreleased.md
- river/meta/__init__.py
- river/meta/target_transform.py
- river/test_.py
> Implement target scaler

- docs/releases/unreleased.md
- river/ensemble/__init__.py
- river/ensemble/voting.py
- river/multioutput/chain.py
- river/utils/estimator_checks.py
Implementing what was asked for in #615.
> Implement voting classifier

- docs/releases/unreleased.md
- river/preprocessing/impute.py
- river/stats/base.py
- river/stats/cov.py
- river/stats/iqr.py
- river/stats/maximum.py
- river/stats/minimum.py
- river/stats/mode.py
- river/stats/ptp.py
- river/stats/quantile.py
- river/stats/sem.py
- river/stats/test_.py
> Add test for newborn stats

- docs/releases/unreleased.md
- river/stats/__init__.py
- river/stats/mad.py
> Implement MAD

- .github/workflows/branch-tests.yml
- .github/workflows/pypi.yml
- .github/workflows/unit-tests.yml
- docs/releases/unreleased.md
- setup.py
> Add support for Python 3.9

- docs/getting-started/getting-started.ipynb
- docs/stylesheets/extra.css
- river/compose/pipeline.py
- river/compose/viz.py
- river/tree/base.py
Of course, every element is clickable.
> Handle wrapper in pipeline viz

- river/drift/ddm.py
- river/drift/eddm.py
- river/drift/hddm_a.py
- river/drift/hddm_w.py
> Docs correction for DDM and variants

- .github/workflows/code-quality.yml
- .github/workflows/dev-docs.yml
- .github/workflows/release-docs.yml
- .github/workflows/unit-tests.yml
- CONTRIBUTING.md
- README.md
- docs/releases/unreleased.md
- river/compose/select.py
Addressing the discussion in #761. Thanks @paulochf for suggesting these changes!
> Remove prejudiced terms

- river/drift/eddm.py
- river/drift/page_hinkley.py
- river/ensemble/adaptive_random_forest.py
- river/metrics/pair_confusion.py
- river/preprocessing/lda.py
- river/tree/nodes/hatc_nodes.py
- river/tree/nodes/hatr_nodes.py
> Use augmented operators

- river/multiclass/occ.py
- river/naive_bayes/gaussian.py
- river/utils/estimator_checks.py
> Fix OCC flaky test

- river/compat/pytorch.py
Hi,
I closed the old PR an created a new one, based on the right branch of the `PyTorchClassifier`.
The tests should now run through.
The comments have helped me, if they don't seem helpful to others we can leave them out.
> Fix PyTorchClassifier variable classes

- docs/releases/unreleased.md
- river/datasets/__init__.py
- river/datasets/bikes.py
- river/datasets/credit_card.py
- river/datasets/elec2.py
- river/datasets/higgs.py
- river/datasets/http.py
- river/datasets/insects.py
- river/datasets/keystroke.py
- river/datasets/malicious_url.py
- river/datasets/movielens100k.py
- river/datasets/music.py
- river/datasets/phishing.py
- river/datasets/restaurants.py
- river/datasets/segment.py
- river/datasets/sms_spam.py
- river/datasets/smtp.py
- river/datasets/solar_flare.py
- river/datasets/taxis.py
- river/datasets/trec07.py
- river/datasets/trump_approval.py
> Add CMU keystroke dataset

- docs/examples/matrix-factorization-for-recommender-systems-part-1.ipynb
> Fix typo in matrix factorization for recommender systems part 1

- river/facto/fm.py
To visualize FM regressor
Added `debug_one` to FM regressor. (If this idea is ok, I'd be happy to add a similar method to other FM regressors)
<details><summary>debug_check.py</summary>
```python
from river import datasets
from river import metrics
from river.evaluate import progressive_val_score
from river import optim
from river import compose
from river import facto
from river import optim
from river import stats
def evaluate(model):
X_y = datasets.MovieLens100K()
metric = metrics.MAE() + metrics.RMSE()
_ = progressive_val_score(X_y, model, metric, print_every=25_000, show_time=True, show_memory=True)
def debug(model):
for x, _ in datasets.MovieLens100K():
report = model.debug_one(x)
print(report)
break
def split_genres(x):
genres = x['genres'].split(', ')
return {f'genre_{genre}': 1 / …
```
> Add debug_one to FM regressor

- docs/releases/unreleased.md
- river/anomaly/base.py
- river/evaluate/progressive_validation.py
- river/metrics/roc_auc.py
- river/utils/inspect.py
Hi all,
based on discussion #794 , you find in this PR a quick-fix so that the `anomaly.AnomalyDetector` works with `Tracks`. 
In addition, I have adapted the `metrics.ROCAUC` metric so that it is now also supported by an `anomaly.AnomalyDetector`.
Best
> Refactor anomaly detection

- docs/releases/unreleased.md
- river/feature_extraction/agg.py
> Add state property to Agg and TargetAgg

- river/compose/select.py
- river/misc/cov_matrix.py
- river/misc/test_cov_matrix.py
- river/naive_bayes/bernoulli.py
- river/naive_bayes/multinomial.py
- setup.py
> Improve covariance matrix

- docs/releases/unreleased.md
- river/proba/__init__.py
- river/proba/base.py
- river/proba/gaussian.py
- river/proba/multinomial.py
- river/proba/time_rolling.py
- river/stats/test_var.py
- river/stats/var.py
> Implement TimeRolling distribution

- docs/releases/unreleased.md
- river/rules/amrules.py
> Fix bug in debug_one (AMRules)

- river/cluster/denstream.py
This PR fixes the question raised in #892.
> [DenStream] Handle the case when point p is not merged and o-micro-cluster is empty

- docs/releases/unreleased.md
- river/evaluate/__init__.py
- river/evaluate/progressive_validation.py
> Implement iter_progressive_val_score

- docs/releases/unreleased.md
Addresses https://github.com/online-ml/river/pull/893#issuecomment-1094355419
> add entry on l1

- docs/releases/unreleased.md
- river/drift/__init__.py
- river/drift/periodic_trigger.py
- river/ensemble/streaming_random_patches.py
- river/tree/nodes/htc_nodes.py
- river/tree/utils.py
It started with the idea of removing the numpy-based random number generators. 
I ended up finding bugs (for instance, if the Poisson weight was zero for some base model, the next ones would not be updated) and making a buried utility accessible (PeriodicTrigger). I also made SRP somewhat robust to missing feature values.
> Streamline SRP{Classifier,Regressor}, remove unneeded numpy usage and add PeriodicTrigger

- docs/releases/unreleased.md
- river/ensemble/adaptive_random_forest.py
- river/ensemble/streaming_random_patches.py
- river/tree/hoeffding_adaptive_tree_classifier.py
- river/tree/hoeffding_adaptive_tree_regressor.py
- river/tree/nodes/arf_htc_nodes.py
- river/tree/nodes/arf_htr_nodes.py
- river/tree/nodes/hatc_nodes.py
- river/tree/nodes/hatr_nodes.py
- river/utils/skmultiflow_utils.py
> Remove unnecessary numpy usage in ARF{C,R} and HAT{C,R}

- river/stream/iter_arff.py
> fix issue #925

- docs/introduction/next-steps.md
Fixed links not working in next-steps.md
> Fixed links not working in next-steps.md

- .github/workflows/release-docs.yml
- river/compose/viz.py
> Some light style change to docs

- .github/CODEOWNERS
Is that ok with you @AdilZouitine? That way you'll get a notification whenever something changes in `stats`. Like that, if you want you can reflect that change in your new library
> Add Adil as stats codeowner

- river/time_series/snarimax.py
- river/time_series/test_snarimax.py
- setup.py
This PR addresses a few more issues Shogo Tanaka find out. He sent me an email:
I discovered a nice pattern, which is to use SymPy to unit test the differencing formulas.
I'll circle back with Shogo to see what he thinks about these changes, and to keep digging if he is still willing :)
> Fix time series differencing

- river/time_series/snarimax.py
- river/time_series/test_snarimax.py
> Some more SNARIMAX fixing 😁

- .github/workflows/pypi.yml
- docs/releases/unreleased.md
Context [here](https://github.com/online-ml/river/discussions/998#discussioncomment-3381323).
> Re-add wheels for Python 3.7

- docs/releases/unreleased.md
- river/covariance/__init__.py
- river/covariance/emp.py
- river/covariance/test_emp.py
- river/stats/kurtosis.py
- river/stats/skew.py
Implemented the inverse covariance matrix 😊
This will make it really straightforward to implement models that need it, such as Bayesian linear regression and the Gaussian anomaly detection. 
In my experiments, the `update_many` method is roughly 10 times faster than `update`. I think it could be much faster if we find the appropriate BLAS method wrapper in scipy. ~But no luck yet~. Edit: I think the [SYRK](https://pyclblas.readthedocs.io/en/latest/SYRK.html) method is what I'm looking for, but I don't see it in scipy.
> Precision matrix

- CONTRIBUTING.md
- docs/releases/unreleased.md
- pyproject.toml
- river/stream/__init__.py
- river/stream/tweet_stream.py
There we go @Dennis1989!
I decided to not use `tweepy` to avoid having an extra dependency (other than `requests`). I implemented a client for the Twitter API v2 [filtered stream](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/introduction) endpoints. I hope that's satisfactory! If not let me know.
@raphaelsty you can take a look too if you're not too busy :)
> Twitter stream

- river/cluster/k_means.py
- river/ensemble/adaptive_random_forest.py
- river/reco/biased_mf.py
- river/reco/funk_mf.py
- river/rules/amrules.py
- river/tree/extremely_fast_decision_tree.py
- river/tree/hoeffding_adaptive_tree_classifier.py
- river/tree/hoeffding_adaptive_tree_regressor.py
- river/tree/hoeffding_tree_classifier.py
- river/tree/hoeffding_tree_regressor.py
- river/tree/isoup_tree_regressor.py
- river/tree/label_combination_hoeffding_tree.py
This is going to be useful for online hyperparameter optimization :)
More parameters can be considered in the future!
> Add more mutable properties

- docs/releases/unreleased.md
- river/stream/__init__.py
- river/stream/twitch_chat_stream.py
> Twitch chat messages stream

- river/stream/twitch_chat_stream.py
Just a few style nitpicks :). I rather do these myself rather than adding loads of comments to an overall good PR
> Style nitpicks in TwitchChatStream

- docs/releases/unreleased.md
- river/sketch/__init__.py
- river/sketch/counter.py
- river/sketch/set.py
One more addition to `river.sketch`!
> Bloom filter to provide approximate set-like operations

- river/imblearn/hard_sampling.py
- river/imblearn/random.py
- river/optim/initializers.py
> Add missing seed type hints

- river/facto/ffm.py
> fix docstrings

- docs/releases/unreleased.md
- river/naive_bayes/gaussian.py
- river/proba/__init__.py
- river/proba/base.py
- river/proba/beta.py
- river/proba/gaussian.py
- river/proba/multinomial.py
- river/tree/splitter/gaussian_splitter.py
> Beta distribution

- docs/releases/unreleased.md
- river/bandit/__init__.py
- river/bandit/envs/candy_cane.py
- river/bandit/evaluate.py
I called it `evaluate` to be consistent with the existing method in the `time_series` module.
I'll make use of this function in a future user guide to reproduce the examples from Sutton and Barto :)
@AdilZouitine can you take a quick pass? Not sure I'm using/copying Gym environments correctly.
> Implement bandit.evaluate

- river/dummy.py
> Add  Krichevsky–Trofimov reference

- .github/workflows/pypi.yml
Hey, 
Quick fix for the cargo error on `manylinux aarch64` when rivers wheels are built 😄
> Fix ci wheels for manylinux aarch64

- river/evaluate/tracks.py
> fix docstring

- river/drift/hddm_w.py
I closed the initial pull request because the formatting of the code got messed up somehow. Redoing the main branch of my fork.
> Fix bug in HDDM_W

- docs/releases/unreleased.md
- river/cluster/textclust.py
- river/preprocessing/scale.py
- river/rules/amrules.py
- river/sketch/heavy_hitters.py
- river/stats/entropy.py
- river/stats/ewmean.py
- river/stats/ewvar.py
Context is [here](https://github.com/online-ml/river/discussions/1030)
> Rename alpha to fading_factor where applicable

- docs/releases/unreleased.md
- river/api.py
- river/conf/__init__.py
- river/conf/interval.py
- river/conf/jackknife.py
- river/linear_model/bayesian_lin_reg.py
- river/stats/quantile.py
The conformal prediction framework is proving to be a reliable to produce predictive intervals. Conformal prediction methods work well because they're non-parametric. Here I introduce one of the simplest methods, which is the Jackknife. Usually it's presented in a batch situation, whereby the training data has to be cross-validated. But doing this online is much more natural!
I recommend [Conformal_Prediction_Presentation.pdf](https://github.com/online-ml/river/files/10098389/Conformal_Prediction_Presentation.pdf) from @leoandeol for anyone looking to get a formal understanding of the conformal prediction framework.
> Introduce conformal predictions (for regression)

- river/tree/hoeffding_tree.py
Hi,
the Hoeffding trees require [Graphviz](https://graphviz.org/download/) to be visualised. Therefore, I would suggest to assert whether it can be imported or not.
Best
> Assert Graphviz import

- river/drift/kswin.py
- river/stats/test_stats.py
> Fix some stuff related to the release of numpy#1.24

- river/anomaly/filter.py
- river/anomaly/hst.py
- river/anomaly/svm.py
- river/evaluate/progressive_validation.py
- river/metrics/roc_auc.py
- river/test_estimators.py
- river/utils/inspect.py
Just some minor changes and examples to show how to evaluate anomaly detectors.
> Ensure progressive validation works with anomaly detectors

- docs/releases/unreleased.md
- river/ensemble/__init__.py
- river/ensemble/bagging.py
- river/ensemble/boosting.py
@MaxHalford  you have asked about using different drift detectors. This class depends on the error rate of ADWIN to reset the worst classifier in the Ensemble, like ADWINBaggingClassifier that is already in River .
> ADWINBoostingClassifier

- river/base/ensemble.py
- river/checks/__init__.py
- river/ensemble/bagging.py
- river/ensemble/boosting.py
- river/model_selection/sh.py
- river/multiclass/occ.py
- river/multiclass/ovr.py
- river/test_estimators.py
> Use clone instead of deepcopy

- .github/workflows/build-river.yml
- .github/workflows/code-quality.yml
- .github/workflows/release-docs.yml
- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- setup.py
https://github.com/charliermarsh/ruff
> Replace flake8 with ruff

- docs/releases/unreleased.md
- river/forest/__init__.py
- river/forest/adaptive_random_forest.py
- river/forest/online_extra_trees.py
- river/tree/nodes/et_nodes.py
- river/tree/nodes/leaf.py
- river/tree/splitter/random_splitter.py
Add online extra trees (OXT) regressor and shorten the names of some algorithms in the forest module.
> [forest] Online Extra Trees

- river/anomaly/base.py
- river/anomaly/filter.py
- river/base/classifier.py
- river/checks/__init__.py
- river/checks/common.py
- river/conf/jackknife.py
- river/drift/retrain.py
- river/ensemble/bagging.py
- river/ensemble/boosting.py
- river/ensemble/streaming_random_patches.py
- river/imblearn/chebyshev.py
- river/imblearn/hard_sampling.py
- river/imblearn/random.py
- river/multiclass/occ.py
- river/multiclass/ovo.py
- river/multiclass/ovr.py
- river/multioutput/chain.py
- Added a test to make sure the methods of each wrapper `**kwargs`, which are then passed down to the wrapped models.
- The test is run systematically for every wrapper.
- Note that tests can be whitelisted if they're too annoying to satisfy.
> Test wrapper methods accept kwargs

- docs/releases/unreleased.md
- river/base/__init__.py
- river/base/drift_detector.py
- river/drift/__init__.py
- river/drift/binary/__init__.py
- river/drift/binary/ddm.py
- river/drift/binary/eddm.py
- river/drift/binary/hddm_a.py
- river/drift/binary/hddm_w.py
- river/drift/dummy.py
- river/drift/retrain.py
- river/drift/test_drift_detectors.py
- river/ensemble/boosting.py
Discussed internally with Saulo.
> Introduce new base classes for binary drift detection

- .github/workflows/build-river.yml
- .github/workflows/docs.yml
- docs/releases/unreleased.md
- river/preprocessing/__init__.py
- river/preprocessing/random_projection.py
- river/preprocessing/test_random_projection.py
Same as scikit-learn's `random_projection` module. This is yet another way to deal with inputs that have many features.
> Add GaussianRandomProjector and SparseRandomProjector

- docs/releases/unreleased.md
- river/metrics/multioutput/macro.py
- river/metrics/multioutput/micro.py
- river/metrics/multioutput/test_multioutput_metrics.py
> Add basic unit tests to metrics.multioutput

- docs/introduction/basic-concepts.md
I fixed a grammatical error that was bugging me.
> Essential spelling fix

- docs/releases/unreleased.md
- river/compose/product.py
- river/compose/test_product.py
- river/compose/union.py
> fix TransformerProduct.transform_many

- docs/releases/unreleased.md
- river/bandit/__init__.py
- river/bandit/base.py
- river/bandit/epsilon_greedy.py
- river/bandit/evaluate.py
- river/bandit/exp3.py
- river/bandit/test_policies.py
- river/bandit/thompson.py
- river/bandit/ucb.py
- river/compose/target_transform.py
- river/model_selection/__init__.py
- river/model_selection/bandit.py
- river/model_selection/base.py
- river/preprocessing/__init__.py
- river/preprocessing/scale.py
- river/preprocessing/scale_target.py
> Implement Exp3 bandit

- docs/parse/__main__.py
- docs/releases/unreleased.md
- river/proba/base.py
- river/proba/beta.py
> Implement Beta CDF function

- docs/releases/unreleased.md
- river/compose/product.py
- river/compose/test_product.py
- river/preprocessing/one_hot.py
- river/tree/isoup_tree_regressor.py
> Make one_hot output sparse dataframes

- river/neighbors/__init__.py
- river/neighbors/ann/swinn.py
- river/neighbors/base.py
- river/neighbors/knn_classifier.py
- river/neighbors/knn_regressor.py
What do you think @smastelini?
> Remove need for FunctionWrapper

- river/bandit/thompson.py
- river/model_selection/bandit.py
- river/model_selection/test_bandit.py
> Fix BanditClassifier

- docs/releases/unreleased.md
- river/cluster/denstream.py
- river/compat/sklearn_to_river.py
- river/compose/pipeline.py
- river/metrics/silhouette.py
- river/neighbors/knn_classifier.py
- river/test_estimators.py
- river/utils/math.py
> Align sklearn to River inputs

- docs/releases/unreleased.md
- river/compose/pipeline.py
> Allow doing stateless inference in mini-batch mode

- docs/releases/unreleased.md
- river/forest/adaptive_random_forest.py
- river/forest/test_amf.py
> Fix ARFClassifier issue with classification metrics

- river/linear_model/bayesian_lin_reg.py
> implement predict_many

- docs/releases/unreleased.md
- river/preprocessing/__init__.py
- river/preprocessing/ordinal.py
@ColdTeapot273K I tried to implement my own interpretation of what you did in #1271. Let me know if it suits your requirements.
Your implementation was understandable, but I found it a bit rough. No worries though!
> Implement ordinal encoder

- docs/releases/unreleased.md
- river/linear_model/bayesian_lin_reg.py
> Implement smooth Bayesian lin reg

- .github/workflows/unit-tests.yml
- docs/releases/unreleased.md
- river/bandit/__init__.py
- river/bandit/base.py
- river/bandit/datasets/__init__.py
- river/bandit/datasets/base.py
- river/bandit/datasets/news.py
- river/bandit/evaluate.py
- river/bandit/lin_ucb.py
- river/bandit/random.py
- river/bandit/ucb.py
First contextual bandit algorithm 🎉
> Implement LinUCB

- docs/releases/unreleased.md
- river/stream/iter_arff.py
> Handle question marks in iter_arff

- docs/releases/unreleased.md
- river/compose/product.py
- river/compose/test_product.py
> Fix transformer product edge case

- river/drift/binary/hddm_a.py
- river/drift/binary/hddm_w.py
- river/drift/retrain.py
Fixes #1315.
I've been able to track down the issue. I have used the MOA code as a reference, so I am unaware of possible minor differences between River and Frouros' code that might result in slight accuracy differences in the code example presented at #1315.
@ngabrek, can you please check if the fix addresses your problem?
> Fix HDDM_*

- river/preprocessing/scale.py
- river/preprocessing/test_scale.py
> Use input dtype in standard scaler transform_many

- river/drift/adwin.py
> expand ADWIN docs

- docs/releases/unreleased.md
- river/utils/rolling.py
- river/utils/test_rolling.py
> Split events into timestamps and datum

- docs/releases/unreleased.md
- river/metrics/confusion.py
- river/metrics/test_confusion.py
> Make confusion matrix work with evaluate module

- river/anomaly/lof.py
- river/anomaly/sad.py
- river/bandit/base.py
- river/bandit/evaluate.py
- river/bandit/thompson.py
- river/bandit/ucb.py
- river/drift/binary/fhddm.py
- river/forest/aggregated_mondrian_forest.py
- river/linear_model/bayesian_lin_reg.py
- river/neighbors/ann/swinn.py
- river/tree/mondrian/mondrian_tree_regressor.py
Mypy was giving off a few errors related to giving a `None` default value to a parameter that was not optional.
This PR aims to fix these errors. No behaviour was changed.
> Fix mypy errors

- .github/workflows/pypi.yml
Fixes #1570.
[Run](https://github.com/online-ml/river/actions/runs/8794826051/job/24134903371) succeeded in 4 hours.
> Update pypa/cibuildwheel in pypi.yml

- docs/releases/unreleased.md
- river/cluster/odac.py
- Update description
- Fix a bug when calculating rnomc
- Add draw() method to see hierarchical cluster's structure as a Graphviz graph
- Working with Var when cluster has only one time-series
> Updates in ODAC code

- docs/introduction/why-use-river.md
> Minor Typo

- river/stats/ewmean.py
- river/stats/ewvar.py
Remove mention of EWMean.mean and EWVar.variance which are never actually used
> Remove mention of EWMean.mean and EWVar.variance

- river/naive_bayes/complement.py
- river/naive_bayes/multinomial.py
> Correct a couple of documentation typos

- river/cluster/k_means.py
This PR fixes some typos found in the code docstrings.
> Typos and spelling in documentation

- river/compose/select.py
A type hint improvement for compose.Select related to #1682
> Improve compose.Select typing (#1682)

- docs/releases/unreleased.md
- river/neighbors/ann/swinn.py
Fixes #1688. Thanks @e10e3 for identifying and creating the issue!
> Remove itertools.cycle usage from neighbors.ann.SWINN

- docs/introduction/basic-concepts.md
Hi, I discovered river today and while I was reading the [basic concepts](https://riverml.xyz/dev/introduction/basic-concepts/) page, I found a typo that I fixed.
> Fixed a small typo in the documentation
